### ISSUE TITLE
description lists are more visible than subsubsections

### ISSUE THREAD

**Issue by DamienCassou** [cdlm/sbabook#14]
![sbabook-description-vs-subsubsection](https://cloud.githubusercontent.com/assets/217543/14426516/d336e3a4-ffef-11e5-946f-2e43a7ba6a78.png)

I have the impression subsubsections should be more visible than description lists, not the opposite. In the example above, the first line is the heading of a subsubsection.

**Comment by cdlm** [comment]
True. I'm not convinced description keys need to be bold either; just sans-serif or monospaced should hopefully be OK, with the spacing and indentation. Maybe adding a dash or a slightly bigger space will be necessary…

**Comment by krono** [comment]
Small caps often is a good choice here, _unless_ it's code
