### ISSUE TITLE
using textcode within subsections does not work

### ISSUE THREAD

**Issue by nicolaihess** [cdlm/sbabook#17]
pillar code like
!!! Using ==CMD-b== to browse
is transformed to latext 
\subsection{Using \textcode{CMD-b} to browse}

but this can not be compiled, as long as \textcode is defined as
\let\textcode\texttt
whereas
\def\textcode{\texttt}
seems to work
(I don't know much about latex)

**Comment by cdlm** [comment]
@nicolaihess this seems to work here, can you check on your side ?
