### ISSUE TITLE
latexmk uses pdflatex by default

### ISSUE THREAD

**Issue by DamienCassou** [cdlm/sbabook#8]
```
$ git clone https://github.com/cdlm/sbabook.git
$ cd sbabook
$ latexmk
[...]
Fatal fontspec error: "cannot-use-pdftex"
```

**Comment by cdlm** [comment]
Strange, there _is_ a `.latexmkrc` file and it does specify LuaLaTeX… I have [a global config file](https://github.com/cdlm/infrastructure/blob/master/dotfiles/latexmkrc) too, maybe that's why?

**Comment by cdlm** [comment]
@DamienCassou can you try adding a line `$pdf_mode = 1;` in `.latexmkrc`? I see I added it for EnterprisePharo so that could be it…

**Comment by DamienCassou** [comment]
Damien Pollet notifications@github.com writes:

> @DamienCassou can you try adding a line `$pdf_mode = 1;` in
> `.latexmkrc`? I see I added it for EnterprisePharo so that could be
> it…

indeed. Adding this line makes it work. Removing it again makes it fail
again.

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
