### ISSUE TITLE
Move \hrefnote from sbabook.tex to sbabook.cls

### ISSUE THREAD

**Issue by DamienCassou** [cdlm/sbabook#9]
The macro `\hrefnote` currently in `sbabook.tex` can be useful in several places. Could you please move that to `sbabook.cls` so that [EnterprisePharo](http://files.pharo.org/books/enterprise-pharo/) can make use of it?

**Comment by DamienCassou** [comment]
I have the impression that some characters should be escaped in `\url`.

Doesn't work:

``` latex
\href{http://www.smalltalkhub.com/#!/~Pier/Pillar}{Pillar}\footnote{\url{http://www.smalltalkhub.com/#!/~Pier/Pillar}}
```

Works

``` latex
\href{http://www.smalltalkhub.com/#!/~Pier/Pillar}{Pillar}\footnote{\url{http://www.smalltalkhub.com/Pier/Pillar}}
```

**Comment by cdlm** [comment]
I think it depends if `\url` is expanded before or after its argument is read by TeX. When it's inside the argument of another macro, the whole thing has already been read once by TeX and any characters that have an effect at read time will be a mess. Condolences to the code that'll be responsible for that in Pillar :p

**Comment by DamienCassou** [comment]
So I guess your macro is not correct because it puts `\url` inside `\footnote`.

**Comment by krono** [comment]
It actually _should_ work. 
It could be, however, be a problem if used inside a macro definition at all.
Btw: there's differences how `\url` works, depending on whether `hyperref`, or `url` is loaded, or both (and in what order)

**Comment by DamienCassou** [comment]
@krono Hi Tobias. I can't make it work, whatever I try. I'm using the `article` document class, and I tried moving the `\usepackage{url}` before and after `\usepackage{hyperref}`. I also tried removing the `\usepackage{url}`. I can only make things compile if I manually protect the `~` and `#` characters inside the `\url` command.

``` latex
\documentclass{article}

\usepackage{url}
\usepackage{hyperref} % undecorated hyperlinks

\begin{document}

\href{http://www.smalltalkhub.com/#!/~Pharo/PharoLauncher}{Launcher}\footnote{\url{http://www.smalltalkhub.com/#!/~Pharo/PharoLauncher}}

\end{document}
```

Do you have an idea?

**Comment by krono** [comment]
What about this?

``` LaTeX
\newcommand\hrefnote[3][]{% inline linked text, plus URL in footnote
  \urldef\tempa{#2}% 
  \href{#2}{#3}\footnote{\tempa\relax #1}}
```

The reason being: (docu from `url.sty`)

> `\url{ }`
> The argument must not contain unbalanced braces. If used in the argument to another command, the \url argument cannot contain any “%”, “#”, or “^^”, or end with “\”.
> `\xyz`
> for the defined-url “`\xyz`”; such a command can be used anywhere, _no matter what characters it contains._

(Emphasis mine; defined-url via `\urldef`)
￼

**Comment by DamienCassou** [comment]
Thanks for the proposal. Does it work for you? I can't make it work either:

``` latex
\documentclass{article}

\usepackage{url}
\newcommand\hrefnote[3][]{% inline linked text, plus URL in footnote
  \urldef\tempa{#2}%
  \href{#2}{#3}\footnote{\tempa\relax #1}}

\usepackage{hyperref} % undecorated hyperlinks
\begin{document}

\hrefnote{http://www.smalltalkhub.com/#!/~Pharo/PharoLauncher}{Launcher}

\end{document}
```

triggers:

```
ERROR: Illegal parameter number in definition of \Url@HyperHook.

--- TeX said ---
<to be read again> 
!
l.11 ...lkhub.com/#!/~Pharo/PharoLauncher}{Launcher}
```

**Comment by krono** [comment]
Yes, I see. Have played around a bit, but it gets hairy with catcodes, futurelets and afterassignments, so I think, it just won't work easily :/

**Comment by DamienCassou** [comment]
Thanks Tobias.

**Comment by cdlm** [comment]
So do we drop this for Enterprise Pharo ?

**Comment by DamienCassou** [comment]
Damien Pollet notifications@github.com writes:

> So do we drop this for Enterprise Pharo ?

yes, we don't need it for Enterprise Pharo. Thanks

## 

Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
